- name: Big Playbook of Fun
  hosts: all
  tasks:
    - name: Print ansible_os_family
      debug: var=ansible_os_family
    - name: Hello World
      assert:
        that:
          - "ansible_os_family == 'Ubuntu'"
          - "my_var == true"
